spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9100/auth/jwks
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-docs
              uri: http://localhost:9100
              predicates:
                - Path=/member/api-docs,/member/swagger-ui.html,/member/swagger-ui/**
              filters:
                - StripPrefix=1
            - id: member
              uri: http://localhost:9100
              predicates:
                - Path=/api/v1/members/**,/api/v1/seller/**,/auth/jwks
            - id: product
              uri: http://localhost:9110
              predicates:
                - Path=/product/**
              filters:
                - StripPrefix=1
            - id: order
              uri: http://localhost:9120
              predicates:
                - Path=/order/**
              filters:
                - StripPrefix=1
            - id: payment
              uri: http://localhost:9130
              predicates:
                - Path=/payment/**
              filters:
                - StripPrefix=1
            - id: settlement-api
              uri: http://localhost:9140
              predicates:
                - Path=/api/v1/settlements/**
            - id: settlement
              uri: http://localhost:9140
              predicates:
                - Path=/settlement/**
              filters:
                - StripPrefix=1

openapi:
  aggregate:
    services:
      member-service: http://localhost:9100/api-docs
      settlement-service: http://localhost:9140/api-docs

