package com.openat.order.domain.model;

public enum OrderFailCode {
  SOLD_OUT,
  DROP_NOT_OPEN,
  DROP_CLOSED,
  LIMIT_EXCEEDED,
  PAYMENT_FAILED,
  PAYMENT_EXPIRED,
  PAYMENT_ALREADY_REFUNDED,
  PAYMENT_NO_RESPONSE,
  PG_ERROR,
  PRODUCT_INTEGRATION_FAILED,
  REFUND_REQUEST_FAILED,
  STOCK_ROLLBACK_FAILED
}
