spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/openat   # 로컬 도커 DB
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092

pg:
  client-key: ${PG_CLIENT_KEY}
  secret-key: ${PG_SECRET_KEY}

services:
  member:
    url: http://localhost:9100                     # 타모듈 localhost
  product:
    url: http://localhost:9110
  order:
    url: http://localhost:9120
  settlement:
    url: http://localhost:9140
