server:
  port: 9130

spring:
  profiles:
    active: local
  application:
    name: payment-service
  jpa:
    properties:
      hibernate:
        default_schema: payment # 스키마 분리
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method