spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}                       # GitHub Secrets → 환경변수
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}

pg:
  secret-key: ${PG_SECRET_KEY}

services:
  member:
    url: http://member:9100
  product:
    url: http://product:9110
  order:
    url: http://order:9120
  settlement:
    url: http://settlement:9140
