{
 "title": "Quick Facts",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  }
 ]
}
{
 "title": "I/O Overview",
 "panels": [
  {
   "title": "Rate",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\"}[1m]))",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_threads_busy{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - BUSY"
    },
    {
     "expr": "tomcat_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - CURRENT"
    },
    {
     "expr": "tomcat_threads_config_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "TOMCAT - MAX"
    },
    {
     "expr": "jetty_threads_busy{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - BUSY"
    },
    {
     "expr": "jetty_threads_current{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - CURRENT"
    },
    {
     "expr": "jetty_threads_config_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - MAX"
    }
   ]
  }
 ]
}
{
 "title": "JVM Memory",
 "panels": [
  {
   "title": "JVM Heap",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\"})",
     "legendFormat": "max"
    },
    {
     "expr": "process_memory_rss_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "pss"
    },
    {
     "expr": "process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "process_memory_swappss_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "swappss"
    },
    {
     "expr": "process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "phys (pss+swap)"
    }
   ]
  },
  {
   "title": "JVM Native Memory",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(process_memory_pss_bytes{application=\"$application\", instance=\"$instance\"} + process_memory_swap_bytes{application=\"$application\", instance=\"$instance\"}  - on(application,instance) sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\"})  by(application,instance)) >= 0",
     "legendFormat": "native"
    }
   ]
  }
 ]
}
{
 "title": "JVM Misc",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=\"$application\", instance=\"$instance\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system-1m"
    },
    {},
    {
     "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_max_fds{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "process_files_open{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Log Events (1m)",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}
{
 "title": "JVM Memory Pools (Heap)",
 "panels": [
  {
   "title": "$jvm_memory_pool_heap",
   "type": "graph",
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}
{
 "title": "JVM Memory Pools (Non-Heap)",
 "panels": [
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "graph",
   "repeat": "jvm_memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", id=\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}
{
 "title": "Garbage Collection",
 "panels": [
  {
   "title": "Collections",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "{{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"$application\", instance=\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "avg {{action}} ({{cause}})"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}})"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=\"$application\", instance=\"$instance\"}[1m])",
     "legendFormat": "promoted"
    }
   ]
  }
 ]
}
{
 "title": "Classloading",
 "panels": [
  {
   "title": "Classes loaded",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class load/unload rate (5m)",
   "type": "graph",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded{application=\"$application\",instance=\"$instance\"}[5m])",
     "legendFormat": "class load rate"
    }
   ]
  }
 ]
}
{
 "title": "Buffer Pools",
 "panels": [
  {
   "title": "Direct Buffers",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count{application=\"$application\", instance=\"$instance\", id=\"direct\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_count{application=\"$application\", instance=\"$instance\", id=\"mapped\"}",
     "legendFormat": "count"
    }
   ]
  }
 ]
}
{
 "title": "공통 — HTTP RED 개요",
 "tags": [
  "openat",
  "common"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP RED — 전 서비스", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app) (rate(http_server_requests_seconds_count{app=~\"$application\"}[1m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Error Rate 5xx by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app) (rate(http_server_requests_seconds_count{app=~\"$application\",status=~\"5..\"}[1m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Avg Latency by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (app)(rate(http_server_requests_seconds_sum{app=~\"$application\"}[5m]))/clamp_min(sum by (app)(rate(http_server_requests_seconds_count{app=~\"$application\"}[5m])),0.001)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Top URIs (5m req rate)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "topk(20, sum by (app,uri,method,status) (rate(http_server_requests_seconds_count{app=~\"$application\"}[5m])))"
    }
   ]
  },
  { "title": "JVM 요약 — 전 서비스", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Heap Used % by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (app)(jvm_memory_used_bytes{app=~\"$application\",area=\"heap\"})*100/clamp_min(sum by (app)(jvm_memory_max_bytes{app=~\"$application\",area=\"heap\"}),1)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Process CPU by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (app)(process_cpu_usage{app=~\"$application\"})",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}